#ifndef NUMO_EXTCONF_H
#define NUMO_EXTCONF_H
#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1
#define HAVE_TYPE_BOOL 1
#define HAVE_TYPE_U_INT8_T 1
#define HAVE_TYPE_U_INT16_T 1
#define HAVE_TYPE_INT32_T 1
#define HAVE_TYPE_U_INT32_T 1
#define HAVE_TYPE_INT64_T 1
#define HAVE_TYPE_U_INT64_T 1
#define HAVE_EXP10 1
#define HAVE_RB_CCOMPLEX 1
#endif
