require_relative "../test_helper"

class Numo::CUDA::DriverTest < Test::Unit::TestCase

  Driver = Numo::CUDA::Driver

  def test_version
    major, minor = Driver.version
    assert { major.is_a?(Integer) }
    assert { minor.is_a?(Integer) }
  end

  def test_create_program
    src = "__global__ void k() {}\n"
    name = "simple.cu"
    headers = []
    include_names = []
    assert_nothing_raised do
      prog = Driver.create_program(src, name, headers, include_names)
    end
  end

  def test_destroy_program
    prog = test_create_program
    assert_nothing_raised do
      Driver.destroy_program(prog)
    end
  end

  def test_compile_program
    prog = test_create_program
    options = []
    assert_nothing_raised do
      Driver.compile_program(prog, options)
    end
    prog
  end

  def test_get_ptx
    prog = test_compile_program
    ptx = Driver.get_ptx(prog)
    assert { ptx =~ /Generated by NVIDIA NVVM Compiler/ }
  end

  def test_get_program_log
    prog = test_compile_program
    log = Driver.get_program_log(prog)
    assert { log.is_a?(String) }
  end
end
