require_relative "../test_helper"

class Numo::CUDA::NVRTCTest < Test::Unit::TestCase

  NVRTC = Numo::CUDA::NVRTC

  def test_version
    major, minor = NVRTC.version
    assert { major.is_a?(Integer) }
    assert { minor.is_a?(Integer) }
  end

  def test_create_program
    src = "__global__ void k() {}\n"
    name = "simple.cu"
    headers = []
    include_names = []
    assert_nothing_raised do
      prog = NVRTC.create_program(src, name, headers, include_names)
    end
  end

  def test_destroy_program
    prog = test_create_program
    assert_nothing_raised do
      NVRTC.destroy_program(prog)
    end
  end

  def test_compile_program
    prog = test_create_program
    options = []
    assert_nothing_raised do
      NVRTC.compile_program(prog, options)
    end
    prog
  end

  def test_get_ptx
    prog = test_compile_program
    ptx = NVRTC.get_ptx(prog)
    assert { ptx =~ /Generated by NVIDIA NVVM Compiler/ }
  end

  def test_get_program_log
    prog = test_compile_program
    log = NVRTC.get_program_log(prog)
    assert { log.is_a?(String) }
  end
end
