# frozen_string_literal: true

require_relative "../test_helper"

module Cumo::CUDA
  class NVRTCTest < Test::Unit::TestCase
    def test_nvrtcVersion
      major, minor = NVRTC.nvrtcVersion
      assert { major.is_a?(Integer) }
      assert { minor.is_a?(Integer) }
    end

    def test_nvrtcCreateProgram
      src = "__global__ void k() {}\n"
      name = "simple.cu"
      headers = []
      include_names = []
      assert_nothing_raised do
        NVRTC.nvrtcCreateProgram(src, name, headers, include_names)
      end
    end

    def test_nvrtcCreateProgram_with_headers
      src = "#include \"my_header.h\"\n__global__ void k(int *p) { *p = MY_CONST; }\n"
      prog = NVRTC.nvrtcCreateProgram(src, "with_header.cu", ["#define MY_CONST 42\n"], ["my_header.h"])
      NVRTC.nvrtcCompileProgram(prog, [])
      assert { NVRTC.nvrtcGetPTX(prog) =~ /Generated by NVIDIA NVVM Compiler/ }
    end

    # headers and include_names arrive as separate arguments, so nothing stops a
    # caller from passing different lengths. nvrtcCreateProgram reads headers.size
    # entries out of *both* arrays.
    def test_nvrtcCreateProgram_with_mismatched_include_names
      src = "__global__ void k() {}\n"
      assert_raise(ArgumentError) do
        NVRTC.nvrtcCreateProgram(src, "s.cu", ["// h\n"], [])
      end
      assert_raise(ArgumentError) do
        NVRTC.nvrtcCreateProgram(src, "s.cu", [], ["h.h"])
      end
      # A wide gap used to read far past the end of include_names and segfault.
      assert_raise(ArgumentError) do
        NVRTC.nvrtcCreateProgram(src, "s.cu", Array.new(4096) { "// h\n" }, Array.new(256) { "h.h" })
      end
    end

    def test_nvrtcCreateProgram_with_non_array
      src = "__global__ void k() {}\n"
      ["not an array", { a: 1 }, 123, nil].each do |bad|
        assert_raise(TypeError) { NVRTC.nvrtcCreateProgram(src, "s.cu", bad, []) }
        assert_raise(TypeError) { NVRTC.nvrtcCreateProgram(src, "s.cu", [], bad) }
      end
    end

    def test_nvrtcCreateProgram_converts_with_to_str
      convertible = Object.new
      def convertible.to_str = "#define MY_CONST 42\n"
      src = "#include \"my_header.h\"\n__global__ void k(int *p) { *p = MY_CONST; }\n"
      prog = NVRTC.nvrtcCreateProgram(src, "to_str.cu", [convertible], ["my_header.h"])
      NVRTC.nvrtcCompileProgram(prog, [])
      assert { NVRTC.nvrtcGetPTX(prog) =~ /Generated by NVIDIA NVVM Compiler/ }
    end

    def test_nvrtcDestroyProgram
      prog = test_nvrtcCreateProgram
      assert_nothing_raised do
        NVRTC.nvrtcDestroyProgram(prog)
      end
    end

    def test_unknown_program_is_rejected
      assert_raise(ArgumentError) { NVRTC.nvrtcDestroyProgram(1) }
      assert_raise(ArgumentError) { NVRTC.nvrtcCompileProgram(1, []) }
      assert_raise(ArgumentError) { NVRTC.nvrtcGetPTX(1) }
      assert_raise(ArgumentError) { NVRTC.nvrtcGetProgramLog(1) }
    end

    def test_destroyed_program_is_rejected
      prog = test_nvrtcCreateProgram
      NVRTC.nvrtcDestroyProgram(prog)
      assert_raise(ArgumentError) { NVRTC.nvrtcDestroyProgram(prog) }
      assert_raise(ArgumentError) { NVRTC.nvrtcGetPTX(prog) }
    end

    def test_nvrtcCompileProgram
      prog = test_nvrtcCreateProgram
      options = []
      assert_nothing_raised do
        NVRTC.nvrtcCompileProgram(prog, options)
      end
      prog
    end

    def test_nvrtcCompileProgram_with_options
      prog = test_nvrtcCreateProgram
      assert_nothing_raised do
        NVRTC.nvrtcCompileProgram(prog, ["-ftz=true", "-DMY_DEFINE=1"])
      end
    end

    def test_nvrtcCompileProgram_with_non_array
      prog = test_nvrtcCreateProgram
      assert_raise(TypeError) { NVRTC.nvrtcCompileProgram(prog, "not an array") }
      assert_raise(TypeError) { NVRTC.nvrtcCompileProgram(prog, nil) }
    end

    def test_nvrtcGetPTX
      prog = test_nvrtcCompileProgram
      ptx = NVRTC.nvrtcGetPTX(prog)
      assert { ptx =~ /Generated by NVIDIA NVVM Compiler/ }
    end

    def test_nvrtcGetProgramLog
      prog = test_nvrtcCompileProgram
      log = NVRTC.nvrtcGetProgramLog(prog)
      assert { log.is_a?(String) }
    end
  end
end
